version: '3.9'
services:

  product:
    depends_on: 
      - product-database
    image: eccom/product
    build: product
    entrypoint: npm run start:dev
    volumes:
      - ./product:/product
    ports:
      - 3000:3000

  account:
    image: eccom/account
    build: account
    entrypoint: npm run start:dev
    volumes:
      - ./account:/app
    ports:
      - 3001:3000

  account-database:
    image: mongo
    container_name: account-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017

  product-database:
    image: mysql
    container_name: product-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=product
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpass
    ports:
      - 3307:3306