version: '3.9'
services:

  product:
    image: eccom/product
    build: product
    volumes:
     - ./product:/app 
    ports:
      - 3000:3000

  account: 
    image: eccom/account
    build: account
    volumes:
      - ./account:/app 
    ports:
      - 3001:3001
      
  
      
      
  account-database:
    image: mongo
    container_name: account-database  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017